pxblue/pxb-database

- deployed/doc-it/R16Roadmap.json
- package-lock.json
- package.json
- src/data/doc-it/R16Roadmap.ts
Have the API to be actually generated in the deployed folder
> Deployed API

- deployed/doc-it/R16Roadmap.json
- src/data/doc-it/R16Roadmap.ts
Changes proposed in this Pull Request:
- Adding a snippet to our roadmap about i18n updates for Q2
> Add update about I18N to roadmap

- README.md
- deployed/doc-it/R16Roadmap.json
- src/data/doc-it/R16Roadmap.ts
> Update to r16 s3

- deployed/doc-it/R16Roadmap.json
- src/data/doc-it/R16Roadmap.ts
- yarn.lock
Fixes # .
Changes proposed in this Pull Request:
- Updates based on the progress in the latest sprint
- Utilize the new tags for 'pre-release' and 'deferred'
> Update roadmap tags based on progress

- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
Changes proposed in this Pull Request:
- Update designer doc to Q3
- 
-
> Update designer docs to Q3

- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
Changes proposed in this Pull Request:
- Bump Design updates to Q3, CLI updates to Q4
> Bump two quarters

- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
For PXBLUE-1370
- Add items for Figma updates (components and paterns)
- Tweak doc it content entries
- Fix typos
- Change a few types (add type, rename applies -> framework)
> Add new content for designer roadmap

- README.md
- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
- Adds designer content
- Updates for sprint 1
- Minor type changes
> Deploy new R17 roadmap

- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
- Mark several items as in progress
- Not sure if that Figma thing counts as "inner sourcing"
> Update roadmap for this sprint

- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
- Update content based on work completed in R17 Sprint 3
> Update content for R7 sprint 3 results

- deployed/doc-it/R17Roadmap.json
- src/data/doc-it/R17Roadmap.ts
> Deploy latest progress

- deployed/doc-it/R18Roadmap.json
- src/data/doc-it/R18Roadmap.ts
- Update for R18 Sprint 2
- Marking a few things to be inner sourced
> Update for R18 Sprint 2

- deployed/doc-it/R18Roadmap.json
- src/data/doc-it/R18Roadmap.ts
Updates from Sprint 4.
- Move the new figma patterns into in progress
- doc-it design patterns finished (first round)
> Update from sprint 4

- deployed/doc-it/R19Roadmap.json
- src/index.ts
- Update the build script to use the R19 source
- Fixes the deployed roadmap
> Build the correct roadmap file

- deployed/doc-it/R19Roadmap.json
- src/data/doc-it/R19Roadmap.ts
> Update roadmap sprint 2 Q1

- deployed/doc-it/R19Roadmap.json
- src/data/doc-it/R19Roadmap.ts
> Update roadmap items for R19 Sprint 3

- deployed/doc-it/R19Roadmap.json
- src/data/doc-it/R19Roadmap.ts
- Done: Nav Rail, Mobile Stepper, User Menu
> Update roadmap item status for sprint 3

- deployed/doc-it/R19Roadmap.json
- src/data/doc-it/R19Roadmap.ts
> Sprint updates

- deployed/doc-it/R16Roadmap.json
- src/data/doc-it/R16Roadmap.ts
- Update items that were finished in R16
> Update finished items from R16

- deployed/doc-it/R16Roadmap.json
- src/data/doc-it/R16Roadmap.ts
- Update from 'applies' to 'framework' and add type definition
- Matches the new format doc-it is expecting
> Fix the types for the R16 roadmap

- deployed/doc-it/R20Roadmap.json
- deployed/doc-it/R21Roadmap.json
- src/data/doc-it/R20Roadmap.ts
- src/data/doc-it/R21Roadmap.ts
- Update the R20 roadmap items
- Add some preliminary items for R21
> Deploy Update for R20S1

- deployed/doc-it/R21Roadmap.json
- deployed/doc-it/R22Roadmap.json
- src/data/doc-it/R21Roadmap.ts
- src/data/doc-it/R22Roadmap.ts
- Add backlog items for R21
Let me know if I missed anything we want to highlight
> Add items for R21

- src/data/doc-it/R21Roadmap.ts
> R21 Sprint 2 Roadmap Updates

- deployed/doc-it/R21Roadmap.json
- src/data/doc-it/R21Roadmap.ts
> Deploy roadmap updates

- deployed/doc-it/R21Roadmap.json
- deployed/doc-it/R22Roadmap.json
- deployed/doc-it/R23Roadmap.json
- src/data/doc-it/R22Roadmap.ts
- src/data/doc-it/R23Roadmap.ts
- src/index.ts
- Update completions for R21
- Move the prior items from R22 to R23
- Update R22 to include migration and training research
> [5] Update completed items for R21, push stuff out to later releases

- deployed/doc-it/R23Roadmap.json
- src/data/doc-it/R23Roadmap.ts
> Fix deffered item in R23
